### ISSUE TITLE
操作有问题

### ISSUE THREAD

**Issue by 694120752** [yingchendas/headercut#1]
九宫格那个选择的框没有按照手指移动的方向滑动
**
canvas画的过程也挺卡的 有解决方案吗
**
测试机：iPhone6 iOS10.2

**Comment by yingchendas** [comment]
你可以更新下插件cropper和mui试试 这个demo是我很早前写的了 我现在在6s系统 版本10.2.1上没出现问题

**Comment by yingchendas** [comment]
https://github.com/fengyuanchen/cropper地址

**Comment by 694120752** [comment]
谢谢 改了cropper里的一些设置解决了
